import { ROLES, LEAD_STATUS } from './constants';

// ===== Mock Users =====
export const mockUsers = [
    {
        id: 'usr_001',
        name: 'Nitin Kumar',
        email: 'admin@lms.com',
        password: 'admin123',
        role: ROLES.ADMIN,
        phone: '9876543210',
        avatar: null,
        isActive: true,
        createdAt: '2026-01-01',
    },
    {
        id: 'usr_002',
        name: 'Priya Sharma',
        email: 'priya@lms.com',
        password: 'sales123',
        role: ROLES.SALES,
        phone: '9876543211',
        avatar: null,
        isActive: true,
        createdAt: '2026-01-15',
    },
    {
        id: 'usr_003',
        name: 'Rahul Verma',
        email: 'rahul@lms.com',
        password: 'sales123',
        role: ROLES.SALES,
        phone: '9876543212',
        avatar: null,
        isActive: true,
        createdAt: '2026-02-01',
    },
    {
        id: 'usr_004',
        name: 'Anjali Gupta',
        email: 'anjali@lms.com',
        password: 'manager123',
        role: ROLES.MANAGER,
        phone: '9876543213',
        avatar: null,
        isActive: true,
        createdAt: '2026-02-10',
    },
    {
        id: 'usr_005',
        name: 'Vikram Singh',
        email: 'vikram@lms.com',
        password: 'sales123',
        role: ROLES.SALES,
        phone: '9876543214',
        avatar: null,
        isActive: false,
        createdAt: '2026-02-15',
    },
];

// ===== Mock Leads =====
export const mockLeads = [
    {
        id: 'lead_001',
        name: 'Rahul Sharma',
        phone: '9876543210',
        email: 'rahul.s@gmail.com',
        course: 'Full Stack Development',
        source: 'Website',
        status: LEAD_STATUS.NEW,
        assignedTo: null,
        remarks: [],
        followUpDate: null,
        createdAt: '2026-03-05',
    },
    {
        id: 'lead_002',
        name: 'Sneha Patel',
        phone: '9876543221',
        email: 'sneha.p@gmail.com',
        course: 'MERN Stack',
        source: 'Facebook',
        status: LEAD_STATUS.ASSIGNED,
        assignedTo: 'usr_002',
        remarks: [],
        followUpDate: null,
        createdAt: '2026-03-04',
    },
    {
        id: 'lead_003',
        name: 'Amit Joshi',
        phone: '9876543222',
        email: 'amit.j@gmail.com',
        course: 'Data Science',
        source: 'Google Ads',
        status: LEAD_STATUS.INTERESTED,
        assignedTo: 'usr_002',
        remarks: [
            {
                date: '2026-03-04',
                response: 'Interested',
                remark: 'Asked about course fees and duration',
                nextFollowUp: '2026-03-05',
            },
        ],
        followUpDate: '2026-03-05',
        createdAt: '2026-03-03',
    },
    {
        id: 'lead_004',
        name: 'Pooja Mehta',
        phone: '9876543223',
        email: 'pooja.m@gmail.com',
        course: 'Digital Marketing',
        source: 'Instagram',
        status: LEAD_STATUS.FOLLOW_UP,
        assignedTo: 'usr_003',
        remarks: [
            {
                date: '2026-03-03',
                response: 'Call Later',
                remark: 'Busy at work, asked to call tomorrow',
                nextFollowUp: '2026-03-05',
            },
        ],
        followUpDate: '2026-03-05',
        createdAt: '2026-03-02',
    },
    {
        id: 'lead_005',
        name: 'Vikash Yadav',
        phone: '9876543224',
        email: 'vikash.y@gmail.com',
        course: 'Python Programming',
        source: 'Referral',
        status: LEAD_STATUS.CONVERTED,
        assignedTo: 'usr_002',
        remarks: [
            {
                date: '2026-03-01',
                response: 'Interested',
                remark: 'Very interested, wants to join next batch',
                nextFollowUp: '2026-03-03',
            },
            {
                date: '2026-03-03',
                response: 'Interested',
                remark: 'Confirmed enrollment. Payment done.',
                nextFollowUp: null,
            },
        ],
        followUpDate: null,
        createdAt: '2026-02-28',
    },
    {
        id: 'lead_006',
        name: 'Neha Agarwal',
        phone: '9876543225',
        email: 'neha.a@gmail.com',
        course: 'UI/UX Design',
        source: 'LinkedIn',
        status: LEAD_STATUS.NOT_INTERESTED,
        assignedTo: 'usr_003',
        remarks: [
            {
                date: '2026-03-04',
                response: 'Not Interested',
                remark: 'Already enrolled in another course',
                nextFollowUp: null,
            },
        ],
        followUpDate: null,
        createdAt: '2026-03-03',
    },
    {
        id: 'lead_007',
        name: 'Ravi Kumar',
        phone: '9876543226',
        email: 'ravi.k@gmail.com',
        course: 'Java Development',
        source: 'Walk-in',
        status: LEAD_STATUS.CALL_NOT_PICKED,
        assignedTo: 'usr_002',
        remarks: [
            {
                date: '2026-03-05',
                response: 'Not Reachable',
                remark: 'Phone switched off. Try again later.',
                nextFollowUp: '2026-03-06',
            },
        ],
        followUpDate: '2026-03-06',
        createdAt: '2026-03-04',
    },
    {
        id: 'lead_008',
        name: 'Suman Devi',
        phone: '9876543227',
        email: 'suman.d@gmail.com',
        course: 'Cloud Computing',
        source: 'Email',
        status: LEAD_STATUS.NEW,
        assignedTo: null,
        remarks: [],
        followUpDate: null,
        createdAt: '2026-03-05',
    },
    {
        id: 'lead_009',
        name: 'Arjun Reddy',
        phone: '9876543228',
        email: 'arjun.r@gmail.com',
        course: 'Cyber Security',
        source: 'Google Ads',
        status: LEAD_STATUS.FOLLOW_UP,
        assignedTo: 'usr_003',
        remarks: [
            {
                date: '2026-03-04',
                response: 'Interested',
                remark: 'Wants demo class first',
                nextFollowUp: '2026-03-05',
            },
        ],
        followUpDate: '2026-03-05',
        createdAt: '2026-03-03',
    },
    {
        id: 'lead_010',
        name: 'Kavita Nair',
        phone: '9876543229',
        email: 'kavita.n@gmail.com',
        course: 'Mobile App Development',
        source: 'Phone Inquiry',
        status: LEAD_STATUS.ASSIGNED,
        assignedTo: 'usr_003',
        remarks: [],
        followUpDate: null,
        createdAt: '2026-03-05',
    },
    {
        id: 'lead_011',
        name: 'Deepak Chauhan',
        phone: '9876543230',
        email: 'deepak.c@gmail.com',
        course: 'Full Stack Development',
        source: 'Website',
        status: LEAD_STATUS.INTERESTED,
        assignedTo: 'usr_002',
        remarks: [
            {
                date: '2026-03-05',
                response: 'Interested',
                remark: 'Looking for weekend batch, follow up Friday',
                nextFollowUp: '2026-03-07',
            },
        ],
        followUpDate: '2026-03-07',
        createdAt: '2026-03-04',
    },
    {
        id: 'lead_012',
        name: 'Meena Kumari',
        phone: '9876543231',
        email: 'meena.k@gmail.com',
        course: 'Data Science',
        source: 'Facebook',
        status: LEAD_STATUS.CLOSED,
        assignedTo: 'usr_002',
        remarks: [
            {
                date: '2026-03-01',
                response: 'Not Interested',
                remark: 'Budget issue. Cannot afford now.',
                nextFollowUp: null,
            },
        ],
        followUpDate: null,
        createdAt: '2026-02-28',
    },
];
